sudo: false

language: node_js

node_js:
  - 'stable'

services:
  - mongodb
  
before_script:
  - sudo /etc/init.d/mongod start

script:
  - npm run test:coveralls

after_success :
  - npm run coverage

notifications:
  email: false
